name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'fc58568782450a92952ac4c6be7299c14d788456'

      - name: Configure
        run: cmake --preset windows-release

      - name: Build
        run: cmake --build build/windows-release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: crystalserver-windows
          path: build/windows-release/bin/
