name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        run: choco install ninja -y

- name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg
          vcpkgGitCommitId: '56bb2411609227288b70117ead2c47585ba07713'

      - name: Configure
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
        run: |
          cmake --preset windows-release -DVCPKG_OVERLAY_PORTS="${{ github.workspace }}/ports"

      - name: Build
        run: cmake --build build/windows-release --config RelWithDebInfo

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: crystalserver-windows
          path: build/windows-release/bin/
